#include <math.h>
#include <stdlib.h>  
#include "opencv2/imgproc/imgproc_c.h"
#include "opencv2/imgproc/imgproc.hpp"
#include "opencv2/core/core_c.h"
#include "opencv2/core/core.hpp"
#include "opencv2/highgui/highgui_c.h"
#include "opencv2/highgui/highgui.hpp"
#include <ctime>    
#include <conio.h>     
#include <iostream>  
#include <fstream>  
#include <sstream>
#include <algorithm>
#include <vector>
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/features2d/features2d.hpp>
#include <list>
#include <direct.h>
#include <unordered_map>
#include "hsv_colors.h"
#include "ImData.h"
#include "rgb_colors.h"
#include "MyLibConstants.h"
#include "SegmentFeatures.h"
#include "SegmentMoments.h"
#include <iomanip>
#include <opencv2/ml/ml.hpp>
#include "getdataclass.h"